########################
## JOE SHUFF BASE UHC ##
########################


### UHC FUNCTIONAL SETTINGS ###
episode-length: 20
perma-day-ep : 5
shrink-size : 100
shrink-ep : 3
shrink-time : 60
show-episodes: true
grace-end-episode: 2
###############################

###### WORLD NAMES #######
UHCWorld : world
hubWorld : hub
###########################

#### HUB SPAWN COORDS ####
hubCentreX : 0
hubCentreY : 0
hubCentreZ : 0
##########################

#### TEAMS SETTING ####
teams : true
friendly-fire: true
#######################

## NETHER PORTAL RADIUS ##
nether-enabled : true
end-enabled: false
##########################

####### GAME RULES #######
apple-rate : 1.0
pearl-rate : 100.0
death-lightning : false
fall-damage : true
pearl-damage : true
absorbtion : true

seconds-until-kick: 30
can-spectate : true
##########################